version: '3'

services:
  postgres_nest:
    image: postgres:9.6
    container_name: postgres_nest
    # environment:
    #   POSTGRES_USER: my_user
    #   POSTGRES_PASSWORD: Passw0rd!
    #   POSTGRES_DB: my_db
    # volumes:
    #   - ./data/postgres:/var/lib/postgresql/data
    #   - ./data/postgres:/data/postgres (?)
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT-5432}:5432"
    restart: always